apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: counter-frontend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: counter-frontend
  minReplicas: 2
  maxReplicas: 4
